name: Publish on PyPI

# By default this action does not push to PyPI. The wheels are available
# as an artifact that can be downloaded and tested locally.

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to publish
        type: string
      pypi:
        description: Publish to PyPI
        default: false
        type: boolean

  workflow_call:
    inputs:
      ref:
        description: Git ref to publish
        type: string
      pypi:
        description: Publish to PyPI
        default: false
        type: boolean

jobs:
  build:
    name: Build distribution files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: python -m pip install --upgrade build pip setuptools

      - name: Build sdist and wheel
        run: python -m build .

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  upload_pypi:
    name: Upload to PyPI (optional)
    if: inputs.pypi
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Push to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
