name: Publish on PyPI

# By default this action does not push to test or production PyPI. The wheels
# are available as an artifact that can be downloaded and tested locally.

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to publish
        default: master
        type: string
      pypi:
        description: Publish to PyPI
        default: false
        type: boolean
      test_pypi:
        description: Publish to TestPyPI
        default: false
        type: boolean

  workflow_call:
    inputs:
      ref:
        description: Git ref to publish
        default: master
        type: string
      pypi:
        description: Publish to PyPI
        default: false
        type: boolean
      test_pypi:
        description: Publish to TestPyPI
        default: false
        type: boolean

jobs:
  build:
    name: Build distribution files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: python -m pip install --upgrade build pip setuptools

      - name: Build sdist and wheel
        run: python -m build .

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  upload_pypi:
    name: Upload to PyPI (optional)
    if: github.event.inputs.pypi == 'true'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Push to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  upload_test_pypi:
    name: Upload to TestPyPI (optional)
    if: github.event.inputs.test_pypi == 'true'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Push to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
