name: Publish release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: The branch to release from
        type: string
        required: true
      version:
        description: The version number to release
        type: string
        required: true

jobs:
  check:
    name: Pre-release checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Check no 'TODO RELEASE' comments remain
        run: |
          if [ -z "$( grep -r --exclude-dir='.*' 'TODO RELEASE' )" ]; then
            exit 0
          else
            exit 1
          fi

      - name: Check version number matches
        run: |
          if [ -z "$( grep 'version = \"${{ inputs.version }}\"' pyproject.toml )" ]; then
            exit 1
          else
            exit 0
          fi

      - name: Check tests pass
        run: |
          pip install '.[test]'
          DATA_REPO_GIT="" pytest test/

  pypi:
    name: Publish release on PyPI
    needs: check
    uses: ./.github/workflows/pypi.yml
    with:
      ref: ${{ inputs.branch }}
      pypi: true
    secrets: inherit

  github_release:
    name: Create GitHub release
    needs: pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create --title ${{ inputs.version }} --target ${{ inputs.branch }} --generate-notes ${{ inputs.version }}
